spring:
  application:
    name: tlias-web-management
  #mysql连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tlias
    username: root
    password: 199585
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求文件大小
      max-request-size: 100MB

#mybatis 相关配置
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关
    map-underscore-to-camel-case: true

#pagehelper 分页合理化-> 自动修复不合理的分页参数
pagehelper:
  reasonable: true
  helper-dialect: mysql

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

# 阿里云oss
aliyun:
  oss:
    endpoint: https://oss-eu-central-1.aliyuncs.com
    bucketName: java-ai-course  # 注意：这里是bucketName，不是bucketname
    region: eu-central-1